location.href = 'https://www.google.com/search?q=gay+porn&oq=lol+lmao&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQABiABDIHCAIQABiABDIHCAMQABiABDIHCAQQABiABDIHCAUQABiABDIHCAYQABiABDIHCAcQABiABDIHCAgQABiABDIHCAkQABiABNIBCDQ3ODBqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8'

